language: node_js
node_js:
  - "14"
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  name: yangjianlinga
  email: yangjianling@tom.com
  on:
    branch: master